# Generated by Django 4.0.6 on 2022-08-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_coaching_mycoaching'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coaching',
        ),
        migrations.DeleteModel(
            name='MyCoaching',
        ),
    ]
